#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Supply version number (such as 1.0.1)"
    exit 1
fi

if [ "$(git status --porcelain | wc --lines)" -ne 0 ]; then
    echo "Error: uncommited changes!"
    exit 1
fi

if [ "$(git rev-parse main)" != "$(git rev-parse origin/main)" ]; then
    echo "Error: main branch not sync with origin/main!"
    exit 1
fi

./gradlew assembleRelease

if [ "$1" != "$(jq '.elements[0].versionName' --raw-output \
	< app/build/outputs/apk/release/output-metadata.json)" ]; then
    echo "Error: version number does not match metadata!"
    exit 1
fi

# TODO: point this at your own itch.io project (this target is the upstream project)
# butler login
# butler push app/build/outputs/apk/release/app-release.apk gardenapple/mitch:android --userversion "$1"
